name: built_vector
version: 0.1.0
description: Generate Flutter vector code from SVG-like files.
homepage: https://github.com/aloisdeniel/built_vector
dependencies:
  args: ^2.3.0
  code_builder: ^4.1.0
  dart_style: ^2.2.1
  path_parsing: ^1.0.0
  recase: ^4.0.0
  source_gen: ^1.2.1
  xml: ^5.3.1
environment:
  sdk: ^2.18.0